const http=require('http');const fs=require('fs');const path=require('path');const facts=require('./report-facts-node');const reportContract=require('./report-server-contract');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,MODEL_TIMEOUT_MS=Number(process.env.REPORT_MODEL_TIMEOUT_MS||180000);
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))}
function body(req){return new Promise((ok,fail)=>{let s='';req.on('data',c=>{s+=c;if(s.length>200000){fail(Error('request too large'));req.destroy()}});req.on('end',()=>{try{ok(JSON.parse(s||'{}'))}catch(e){fail(Error('invalid json'))}});req.on('error',fail)})}
function mime(file){return file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':file.endsWith('.json')?'application/json; charset=utf-8':'application/octet-stream'}
function responseText(x){if(typeof x?.output_text==='string'&&x.output_text.trim())return x.output_text;for(const item of x?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&typeof c.text==='string')return c.text;return ''}
async function callOpenAI(prompt){const key=process.env.OPENAI_API_KEY;if(!key)throw Error('AI report service is not configured');const model=process.env.REPORT_MODEL;if(!model)throw Error('AI report model is not configured');const schema=JSON.parse(fs.readFileSync(path.join(ROOT,'report-schema.json'),'utf8'));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),MODEL_TIMEOUT_MS);let r;try{r=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:controller.signal,headers:{'content-type':'application/json','authorization':`Bearer ${key}`},body:JSON.stringify({model,store:false,input:[{role:'system',content:'Return only the requested premium report JSON. Follow the supplied facts and rules exactly.'},{role:'user',content:JSON.stringify(prompt)}],text:{format:{type:'json_schema',name:'saju_mbti_premium_report',strict:true,schema}}})});}catch(e){if(e?.name==='AbortError')throw Error('AI report service timed out');throw Error('AI report service request failed')}finally{clearTimeout(timer)}if(!r.ok){let detail='';try{const err=await r.json();detail=String(err?.error?.message||err?.error?.type||'').replace(/[\r\n]+/g,' ').slice(0,500)}catch{}console.error('[OpenAI API error]',{status:r.status,model,error:detail||'no error detail'});throw Error(`AI report service error (${r.status})`)}const x=await r.json(),text=responseText(x);if(!text)throw Error('AI report service returned no output');try{return JSON.parse(text)}catch{throw Error('AI report service returned invalid report data')}}
async function callModel(prompt){if(process.env.REPORT_MODEL_URL){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),MODEL_TIMEOUT_MS);let r;try{r=await fetch(process.env.REPORT_MODEL_URL,{method:'POST',signal:controller.signal,headers:{'content-type':'application/json',...(process.env.REPORT_MODEL_KEY?{'authorization':`Bearer ${process.env.REPORT_MODEL_KEY}`}:{})},body:JSON.stringify(prompt)});}catch(e){if(e?.name==='AbortError')throw Error('AI report service timed out');throw Error('AI report service request failed')}finally{clearTimeout(timer)}if(!r.ok)throw Error(`AI report service error (${r.status})`);return r.json()}return callOpenAI(prompt)}
async function handler(req,res){try{req.setTimeout?.(MODEL_TIMEOUT_MS+15000);res.setTimeout?.(MODEL_TIMEOUT_MS+15000);if(req.method==='POST'&&req.url==='/api/calculate'){const input=await body(req),packet=facts.build(input,2027);return json(res,packet.status==='ready'?200:422,packet)}if(req.method==='POST'&&req.url==='/api/report'){const payload=await body(req),a=payload.analysisInput;if(a?.status!=='ready'||!a.calculationInput)return json(res,422,{status:'blocked',errors:['validated calculation input is missing']});const result=await reportContract.generate(a.calculationInput,callModel);return json(res,result.status==='ready'?200:422,result.status==='ready'?result.report:result)}if(req.method==='GET'){let p=req.url==='/'?'/index.html':req.url.split('?')[0];p=path.normalize(p).replace(/^([.][.][/\\])+/, '');const file=path.join(ROOT,p);if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'content-type':mime(file)});return fs.createReadStream(file).pipe(res)}res.writeHead(405);res.end('Method not allowed')}catch(e){const safe=/^(AI report service|invalid json|request too large)/.test(String(e.message||''))?e.message:'server error';json(res,500,{status:'error',message:safe})}}
http.createServer(handler).listen(PORT,()=>console.log(`saju-mbti server listening on ${PORT}`));